[package]
name = "simple-msg-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket_okapi = { version = "=0.8.0", features = ["swagger", "rapidoc"] }
rocket = "=0.5.0"
serde = "1.0"
